spring:
  datasource:
    url: ${JDBC_URL}
    username: ${LOGIN}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
balance:
  sql_dialect: org.hibernate.dialect.PostgreSQL9Dialect
admin:
  login: admin
  password: admin
vk:
  serviceKey: ${VK_SERVICE_KEY}
  confirmationString: ${VK_CONFIRMATION_STRING}
  secretCode: ${VK_SECRET_CODE}
  group_id: ${VK_GROUP_ID}
telegram:
  channelId: ${TELEGRAM_CHANNEL_ID}
